### ISSUE TITLE
Version 8.4.0 Android have issue!

### ISSUE THREAD

**Issue by Kroberus** [foxitsoftware/cordova-plugin-foxitpdf#23]
@xinqiangSong 
When I build the project, I have a problem
but in version 8.3.0 there is no problem
Please support me! Thanks
![foxit-84](https://user-images.githubusercontent.com/118706956/233238898-23f4aa25-1581-40d0-beea-55dbb17f806f.PNG)

Environment project in use:
cordova-android: 9.1.0
![image](https://user-images.githubusercontent.com/118706956/233239478-6a40f046-467b-49bb-88d6-fb671b6131c6.png)

**Comment by xinqiangSong** [comment]
> @xinqiangSong When I build the project, I have a problem but in version 8.3.0 there is no problem Please support me! Thanks ![foxit-84](https://user-images.githubusercontent.com/118706956/233238898-23f4aa25-1581-40d0-beea-55dbb17f806f.PNG)
> 
> Environment project in use: cordova-android: 9.1.0 ![image](https://user-images.githubusercontent.com/118706956/233239478-6a40f046-467b-49bb-88d6-fb671b6131c6.png)

----------------
@Kroberus 
Due to changes in the Android storage mechanism, accessing files on devices larger than Android 10 requires permission application， you can refer to:

https://developer.android.com/about/versions/11/privacy/storage
https://developer.android.com/training/data-storage/manage-all-files

You can change your targetsdkVersion to 30, but after changing this, your app's storage behavior may change.  If you don't want to change it, you can only comment out these judgments, because this method is only available above 30:

![image](https://user-images.githubusercontent.com/8839082/233250533-f44d9df0-e543-4da5-917a-cf66e5cfd3f9.png)
